### ISSUE TITLE
Is Windows supported?

### ISSUE THREAD

**Issue by hao-peng-sdl** [webdriverio/cucumber-boilerplate#31]
Following the instruction on my Windows 7 (with all the necessary packages installed), I struggled to get the run.js to work with Node or Mocha.

Is windows supported and if so, what commands should I use?

**Comment by alexcason** [comment]
@hao-peng-sdl It looks like the problem preventing it from working in Windows is that the `run.js` file attempts to run a shell script which was resulting in the following error:

    c:\code\ce-learningenglish-tests\node_modules\.bin\_mocha:2
    basedir=`dirname "$0"`
            ^
    SyntaxError: Unexpected token ILLEGAL
        at exports.runInThisContext (vm.js:73:16)
        at Module._compile (module.js:443:25)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3

I got it working by making the following changes:

1. In `test/run.js` change line 10 from

        args = [path.join(__dirname, '..', 'node_modules', '.bin', '_mocha')],
to

        args = [path.join(__dirname, '..', 'node_modules', 'mocha', 'bin', '_mocha')],

2. In `test/config.js` change line 13 from

        host: '0.0.0.0',
to

        host: '127.0.0.1',

You should then be able to run your tests by starting the selenium server using `npm run-script server` and `./test/run.js`.

**Comment by branneman** [comment]
I've tested it on my Mac and a Windows machine, and the changes @alexcason suggests work on both, can this be fixed? Do you want a PR for it? Maybe @alexcason wants to make the PR?

**Comment by christian-bromann** [comment]
@branneman a PR would be great yes!

**Comment by alexcason** [comment]
@branneman @christian-bromann Sure, I'll send a PR with the changes outlined above shortly.

**Comment by alexcason** [comment]
I've submitted a PR which makes the changes outlined above

There is a further issue preventing the standard boilerplate tests from running on Windows. The `npm run-script server` command doesn't start both selenium and the http server which means that the tests on the demo site don't work.

The issue appears to be as a result of the & in the command not working correctly on Windows.

**Comment by branneman** [comment]
True, I found that as well, my (quick-hack) solution was turning the `scripts` section in the `package.json` into separate commands:

```json
"scripts": {
    "postinstall": "selenium-standalone install",
    "phantomjs": "phantomjs",
    "start-selenium": "selenium-standalone start",
    "start-server": "http-server ./demo-app",
    "test" : "node test/run.js"
  }
```

However, I think a true solution would be something like this: https://github.com/branneman/argus-eyes/blob/master/package.json#L9-L13

But for this to work, you would need to implement a server-controller, like this: https://github.com/branneman/argus-eyes/blob/master/tests/mock-server/server-controller.js

Thoughts?

**Comment by alexcason** [comment]
I don't think separate commands for `selenium-standalone` and `http-server` would be too bad. It keeps things quite simple as well.

I think that one of the first things a user is likely to do is to direct the tests at their own site, which means that they won't need to run http-server anymore.

@branneman @christian-bromann What do you think? If you're happy with that approach I can separate the commands and update the readme.

**Comment by branneman** [comment]
I'm good with either! :+1:

**Comment by christian-bromann** [comment]
> happy with that approach I can separate the commands and update the readme.

Yes, sounds good to me!

> you would need to implement a server-controller

@branneman why do we need a server controller if we can use http-server? We only need to save the PID in a temporary file in order to shut down the server in the posttest hook

**Comment by branneman** [comment]
The only thing the server-controller does is save and remove the pid file. You can however replace the [server.js](https://github.com/branneman/argus-eyes/blob/master/tests/mock-server/server.js) with the `http-server` module.

What I did with argus-eyes, is I wanted to have a single `npm test` command, that makes sure a server is running beforehand. But since the `http-server` command will run as long as the server runs, my `scripts.pretest` would never end. Thus I needed a startup script which can actually end, but keep the server running. Think how Apache does this `apachectl start` and `apachectl stop`.

But. With argus-eyes I've got only 1 such dependency that needs to run, the test server. With the cucumber-boilerplate there are actually 2 dependencies (http-server and selenium) that needs to keep running in the background, thus it would need this controller script twice.

Implementing this all would give you a single command to run everything (`npm test`), but as was pointed out users would likely run this asap on their own site. Clustering the 3 commands into one will make it harder for a user to take the example http server out.

So, I think the separate scripts are fine :)

**Comment by branneman** [comment]
Lastly, imo this issue can't be closed yet, as long as there is no solution implemented.
